name: CICD

env:
  MIN_SUPPORTED_RUST_VERSION: "1.51.0"
  CICD_INTERMEDIATES_DIR: "_cicd-intermediates"

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Minimum supported rust version
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install rust toolchain (v${{ env.MIN_SUPPORTED_RUST_VERSION }})
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.MIN_SUPPORTED_RUST_VERSION }}
          default: true
          profile: minimal
          components: clippy
      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
  test:
    name: ${{ matrix.job.os }} (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: ubuntu-18.04
            target: aarch64-unknown-linux-gnu
          - os: ubuntu-18.04
            target: i686-unknown-linux-gnu
          - os: ubuntu-18.04
            target: i686-unknown-linux-musl
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-musl
          - os: macos-10.15
            target: x86_64-apple-darwin
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install prerequisites
        shell: bash
        run: |
          case ${{ matrix.job.target }} in
            aarch64-unknown-linux-gnu) sudo apt-get -y update ; sudo apt-get -y install gcc-aarch64-linux-gnu ;;
          esac
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal
      - name: Show version information (Rust, cargo, GCC)
        shell: bash
        run: |
          gcc --version || true
          rustup -V
          rustup toolchain list
          rustup default
          cargo -V
          rustc -V
      # - name: Build
      #   uses: actions-rs/cargo@v1
      #   with:
      #     use-cross: ${{ matrix.job.use-cross }}
      #     command: build
      #     args: --release --target=${{ matrix.job.target }}
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: "0.15.0"
          args: "--doc --lib --tests --bin gitlab-rescue -o Html"
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: run-${{ matrix.job.target }}
          parallel: true
